### PR TITLE
Mojave / Catalina support

### PR DESCRIPTION
**Pull request by ccollins476ad**
This PR replaces the use of XPC services with the "cbgo" library
(CoreBluetooth Go).  This PR consists of a single massive commit and for that I apologize.

The cbgo library (https://github.com/JuulLabs-OSS/cbgo) is new and likely buggy.  As the README indicates, there are definitely memory leaks that will need to be fixed.  That said, I have tested this PR with the go-ble example apps and the newtmgr tool (https://github.com/apache/mynewt-newtmgr) without issue.

### CODE REVIEW

**Comment by deadprogram** [comment]
This is very exciting contribution, and I look forward to testing it out. Thanks for working on it @ccollins476ad

**Comment by alexhowarth** [comment]
I am currently using the https://github.com/JuulLabs-OSS/ble fork of this project on macOS Catalina. This is an awesome contribution. 

> This is very exciting contribution, and I look forward to testing it out. Thanks for working on it @ccollins476ad

+1

I'm currently using the https://github.com/JuulLabs-OSS/ble fork on macOS Catalina.

**Comment by phelpsw** [comment]
Any updates here?  This would be great to merge.

**Comment by estutzenberger** [comment]
Apologies for the long delay in responding to this PR. This work looks good. I'm not easily able to test it but I'm happy to merge it based on the feedback I have seen thus far on the PR and issue.

**Pull request merged**
